

let positions = [
  {
    "id": 0,
    "reportsTo": "Porter Mendoza",
    "title": "Guidance Counselor (1)",
    "positionType": "Teacher - Sci - (5-8)",
    "locationFirst": "Middle School",
    "locationTwo": "High School",
    "location": "Middle School High School",
    "internal": true,
    "status": "New Application",
    "budgetCode": "6050-District Office"
  },
  {
    "id": 1,
    "reportsTo": "Cathryn Hays",
    "title": "Data Coordinator",
    "positionType": "PSR Teacher (K-4)",
    "locationFirst": "Elementary",
    "locationTwo": "Elementary",
    "location": "Elementary Elementary",
    "internal": false,
    "status": "Hiring in Process",
    "budgetCode": "6040-Non Instructional Support"
  },
  {
    "id": 2,
    "reportsTo": "Duncan Mccray",
    "title": "Athletic Coach",
    "positionType": "Teacher - Specialty (K-4)",
    "locationFirst": "Elementary",
    "locationTwo": "High School",
    "location": "Elementary High School",
    "internal": true,
    "status": "Keep on File",
    "budgetCode": "6020-Instructional Support"
  },
  {
    "id": 3,
    "reportsTo": "Langley Woodward",
    "title": "Data Coordinator",
    "positionType": "Executive Director",
    "locationFirst": "High School",
    "locationTwo": "Elementary",
    "location": "High School Elementary",
    "internal": false,
    "status": "Screening",
    "budgetCode": "6020-Instructional Support"
  },
  {
    "id": 4,
    "reportsTo": "Marquita Kent",
    "title": "Kindergarten",
    "positionType": "Executive Director",
    "locationFirst": "BuffSci 2",
    "locationTwo": "BuffSci 2",
    "location": "BuffSci 2 BuffSci 2",
    "internal": false,
    "status": "Screening",
    "budgetCode": "6070-Tax"
  },
  {
    "id": 5,
    "reportsTo": "Brandie Dickson",
    "title": "Business Office - Support",
    "positionType": "Teacher - Sci - (5-8)",
    "locationFirst": "Elementary",
    "locationTwo": "Elementary",
    "location": "Elementary Elementary",
    "internal": true,
    "status": "Hiring in Process",
    "budgetCode": "6040-Non Instructional Support"
  },
  {
    "id": 6,
    "reportsTo": "Barron Norris",
    "title": "STEM (9)",
    "positionType": "Executive Director",
    "locationFirst": "Elementary",
    "locationTwo": "Elementary",
    "location": "Elementary Elementary",
    "internal": false,
    "status": "Screening",
    "budgetCode": "6050-District Office"
  },
  {
    "id": 7,
    "reportsTo": "Hernandez Livingston",
    "title": "STEM (9)",
    "positionType": "Support Teacher K-4",
    "locationFirst": "High School",
    "locationTwo": "Middle School",
    "location": "High School Middle School",
    "internal": true,
    "status": "Keep on File",
    "budgetCode": "6010-Base"
  },
  {
    "id": 8,
    "reportsTo": "Kay Conley",
    "title": "PIG/Econ",
    "positionType": "Office Boy",
    "locationFirst": "High School",
    "locationTwo": "High School",
    "location": "High School High School",
    "internal": false,
    "status": "New Application",
    "budgetCode": "6060-Administrators"
  },
  {
    "id": 9,
    "reportsTo": "Oneil Cummings",
    "title": "Data Coordinator",
    "positionType": "Teacher - Specialty (K-4)",
    "locationFirst": "BuffSci 2",
    "locationTwo": "Elementary",
    "location": "BuffSci 2 Elementary",
    "internal": false,
    "status": "New Application",
    "budgetCode": "6070-Tax"
  },
  {
    "id": 10,
    "reportsTo": "Osborn Carey",
    "title": "Guidance Counselor (1)",
    "positionType": "Support Teacher 5-8",
    "locationFirst": "Middle School",
    "locationTwo": "BuffSci 2",
    "location": "Middle School BuffSci 2",
    "internal": true,
    "status": "New Application",
    "budgetCode": "6070-Tax"
  },
  {
    "id": 11,
    "reportsTo": "Lottie Sims",
    "title": "Science Teacher",
    "positionType": "Support Teacher 5-8",
    "locationFirst": "Elementary",
    "locationTwo": "Middle School",
    "location": "Elementary Middle School",
    "internal": true,
    "status": "New Application",
    "budgetCode": "6040-Non Instructional Support"
  },
  {
    "id": 12,
    "reportsTo": "Jenkins Little",
    "title": "Athletic Coach",
    "positionType": "Teacher - Specialty (K-4)",
    "locationFirst": "BuffSci 2",
    "locationTwo": "Middle School",
    "location": "BuffSci 2 Middle School",
    "internal": true,
    "status": "New Application",
    "budgetCode": "6040-Non Instructional Support"
  },
  {
    "id": 13,
    "reportsTo": "Stefanie Bowman",
    "title": "Copy Center",
    "positionType": "Nurse",
    "locationFirst": "Middle School",
    "locationTwo": "Elementary",
    "location": "Middle School Elementary",
    "internal": false,
    "status": "Interviewed",
    "budgetCode": "6020-Instructional Support"
  },
  {
    "id": 14,
    "reportsTo": "Elsie Gibbs",
    "title": "Business Office - Support",
    "positionType": "Help Desk Technician",
    "locationFirst": "Middle School",
    "locationTwo": "High School",
    "location": "Middle School High School",
    "internal": false,
    "status": "Hiring in Process",
    "budgetCode": "6040-Non Instructional Support"
  },
  {
    "id": 15,
    "reportsTo": "Cohen Madden",
    "title": "Athletic Coach",
    "positionType": "Teacher - Sci - (5-8)",
    "locationFirst": "BuffSci 2",
    "locationTwo": "BuffSci 2",
    "location": "BuffSci 2 BuffSci 2",
    "internal": false,
    "status": "Interview Scheduled",
    "budgetCode": "6010-Base"
  },
  {
    "id": 16,
    "reportsTo": "Price Sweet",
    "title": "STEM (9)",
    "positionType": "Support Teacher 5-8",
    "locationFirst": "Elementary",
    "locationTwo": "Middle School",
    "location": "Elementary Middle School",
    "internal": true,
    "status": "New Application",
    "budgetCode": "6020-Instructional Support"
  },
  {
    "id": 17,
    "reportsTo": "Rosa Mendez",
    "title": "PIG/Econ",
    "positionType": "Help Desk Technician",
    "locationFirst": "BuffSci 2",
    "locationTwo": "High School",
    "location": "BuffSci 2 High School",
    "internal": false,
    "status": "Screening",
    "budgetCode": "6070-Tax"
  },
  {
    "id": 18,
    "reportsTo": "Mccall Wallace",
    "title": "Business Office - Support",
    "positionType": "Support Teacher 5-8",
    "locationFirst": "BuffSci 2",
    "locationTwo": "BuffSci 2",
    "location": "BuffSci 2 BuffSci 2",
    "internal": true,
    "status": "Keep on File",
    "budgetCode": "6040-Non Instructional Support"
  },
  {
    "id": 19,
    "reportsTo": "Patton Frank",
    "title": "Math Specialist (4)",
    "positionType": "Office Boy",
    "locationFirst": "BuffSci 2",
    "locationTwo": "BuffSci 2",
    "location": "BuffSci 2 BuffSci 2",
    "internal": true,
    "status": "Withdrawn",
    "budgetCode": "6070-Tax"
  },
  {
    "id": 20,
    "reportsTo": "Hewitt Delaney",
    "title": "Math Specialist (4)",
    "positionType": "Support Teacher K-4",
    "locationFirst": "High School",
    "locationTwo": "BuffSci 2",
    "location": "High School BuffSci 2",
    "internal": true,
    "status": "Hiring in Process",
    "budgetCode": "6060-Administrators"
  },
  {
    "id": 21,
    "reportsTo": "Alvarez Nielsen",
    "title": "Math Specialist (4)",
    "positionType": "Support Teacher K-4",
    "locationFirst": "BuffSci 2",
    "locationTwo": "Middle School",
    "location": "BuffSci 2 Middle School",
    "internal": false,
    "status": "Hiring in Process",
    "budgetCode": "6070-Tax"
  },
  {
    "id": 22,
    "reportsTo": "Hancock Rivera",
    "title": "Geo (4)",
    "positionType": "Support Teacher K-4",
    "locationFirst": "BuffSci 2",
    "locationTwo": "Elementary",
    "location": "BuffSci 2 Elementary",
    "internal": false,
    "status": "New Application",
    "budgetCode": "6060-Administrators"
  },
  {
    "id": 23,
    "reportsTo": "Adrienne Stewart",
    "title": "PIG/Econ",
    "positionType": "Executive Director",
    "locationFirst": "BuffSci 2",
    "locationTwo": "BuffSci 2",
    "location": "BuffSci 2 BuffSci 2",
    "internal": false,
    "status": "Interview Scheduled",
    "budgetCode": "6020-Instructional Support"
  },
  {
    "id": 24,
    "reportsTo": "Harrison Carson",
    "title": "Athletic Coach",
    "positionType": "Director",
    "locationFirst": "BuffSci 2",
    "locationTwo": "Elementary",
    "location": "BuffSci 2 Elementary",
    "internal": false,
    "status": "Hiring in Process",
    "budgetCode": "6010-Base"
  },
  {
    "id": 25,
    "reportsTo": "Yang Forbes",
    "title": "Copy Center",
    "positionType": "Director",
    "locationFirst": "Middle School",
    "locationTwo": "High School",
    "location": "Middle School High School",
    "internal": true,
    "status": "Hiring in Process",
    "budgetCode": "6070-Tax"
  },
  {
    "id": 26,
    "reportsTo": "Colon Stokes",
    "title": "Science Teacher",
    "positionType": "Executive Director",
    "locationFirst": "Middle School",
    "locationTwo": "BuffSci 2",
    "location": "Middle School BuffSci 2",
    "internal": false,
    "status": "Interviewed",
    "budgetCode": "6040-Non Instructional Support"
  },
  {
    "id": 27,
    "reportsTo": "Marisa Morris",
    "title": "CFO",
    "positionType": "Executive Director",
    "locationFirst": "Elementary",
    "locationTwo": "Elementary",
    "location": "Elementary Elementary",
    "internal": true,
    "status": "Hiring in Process",
    "budgetCode": "6070-Tax"
  },
  {
    "id": 28,
    "reportsTo": "Fisher Hanson",
    "title": "Data Coordinator",
    "positionType": "Office Boy",
    "locationFirst": "High School",
    "locationTwo": "High School",
    "location": "High School High School",
    "internal": true,
    "status": "Keep on File",
    "budgetCode": "6060-Administrators"
  },
  {
    "id": 29,
    "reportsTo": "Erma Espinoza",
    "title": "Athletic Coach",
    "positionType": "Teacher - Elementary",
    "locationFirst": "BuffSci 2",
    "locationTwo": "Middle School",
    "location": "BuffSci 2 Middle School",
    "internal": false,
    "status": "New Application",
    "budgetCode": "6030-General Support"
  },
  {
    "id": 30,
    "reportsTo": "Andrea Wynn",
    "title": "Guidance Counselor (1)",
    "positionType": "Receptionist",
    "locationFirst": "High School",
    "locationTwo": "BuffSci 2",
    "location": "High School BuffSci 2",
    "internal": false,
    "status": "Screening",
    "budgetCode": "6070-Tax"
  },
  {
    "id": 31,
    "reportsTo": "Aguilar Thomas",
    "title": "Geo (4)",
    "positionType": "Executive Director",
    "locationFirst": "BuffSci 2",
    "locationTwo": "Middle School",
    "location": "BuffSci 2 Middle School",
    "internal": false,
    "status": "Screening",
    "budgetCode": "6040-Non Instructional Support"
  },
  {
    "id": 32,
    "reportsTo": "Mccormick Rasmussen",
    "title": "Cleaning Crew",
    "positionType": "Executive Director",
    "locationFirst": "High School",
    "locationTwo": "BuffSci 2",
    "location": "High School BuffSci 2",
    "internal": false,
    "status": "Interviewed",
    "budgetCode": "6050-District Office"
  },
  {
    "id": 33,
    "reportsTo": "Alba Ross",
    "title": "Social Worker (6)",
    "positionType": "Teacher - Elementary",
    "locationFirst": "High School",
    "locationTwo": "BuffSci 2",
    "location": "High School BuffSci 2",
    "internal": false,
    "status": "Withdrawn",
    "budgetCode": "6010-Base"
  },
  {
    "id": 34,
    "reportsTo": "Rosa Peterson",
    "title": "Business Office - Support",
    "positionType": "Office Boy",
    "locationFirst": "High School",
    "locationTwo": "Elementary",
    "location": "High School Elementary",
    "internal": true,
    "status": "Interview Scheduled",
    "budgetCode": "6040-Non Instructional Support"
  },
  {
    "id": 35,
    "reportsTo": "Kinney Rush",
    "title": "Data Coordinator",
    "positionType": "Teacher - Sci - (5-8)",
    "locationFirst": "BuffSci 2",
    "locationTwo": "Middle School",
    "location": "BuffSci 2 Middle School",
    "internal": false,
    "status": "Withdrawn",
    "budgetCode": "6060-Administrators"
  },
  {
    "id": 36,
    "reportsTo": "Liliana Roach",
    "title": "Business Office - Support",
    "positionType": "Executive Director",
    "locationFirst": "High School",
    "locationTwo": "High School",
    "location": "High School High School",
    "internal": false,
    "status": "Screening",
    "budgetCode": "6050-District Office"
  },
  {
    "id": 37,
    "reportsTo": "John Case",
    "title": "Data Coordinator",
    "positionType": "Teacher - Elementary",
    "locationFirst": "BuffSci 2",
    "locationTwo": "Elementary",
    "location": "BuffSci 2 Elementary",
    "internal": false,
    "status": "Hiring in Process",
    "budgetCode": "6010-Base"
  },
  {
    "id": 38,
    "reportsTo": "Dolores Galloway",
    "title": "PIG/Econ",
    "positionType": "PSR Teacher (K-4)",
    "locationFirst": "BuffSci 2",
    "locationTwo": "Elementary",
    "location": "BuffSci 2 Elementary",
    "internal": false,
    "status": "Interviewed",
    "budgetCode": "6010-Base"
  },
  {
    "id": 39,
    "reportsTo": "Shelly Bryant",
    "title": "PIG/Econ",
    "positionType": "Help Desk Technician",
    "locationFirst": "BuffSci 2",
    "locationTwo": "Middle School",
    "location": "BuffSci 2 Middle School",
    "internal": false,
    "status": "Hiring in Process",
    "budgetCode": "6020-Instructional Support"
  },
  {
    "id": 40,
    "reportsTo": "Leonard Dillon",
    "title": "Athletic Coach",
    "positionType": "Receptionist",
    "locationFirst": "BuffSci 2",
    "locationTwo": "High School",
    "location": "BuffSci 2 High School",
    "internal": false,
    "status": "Hiring in Process",
    "budgetCode": "6050-District Office"
  },
  {
    "id": 41,
    "reportsTo": "Reeves Sawyer",
    "title": "Math Specialist (4)",
    "positionType": "Director",
    "locationFirst": "High School",
    "locationTwo": "Elementary",
    "location": "High School Elementary",
    "internal": false,
    "status": "Hiring in Process",
    "budgetCode": "6040-Non Instructional Support"
  },
  {
    "id": 42,
    "reportsTo": "Cervantes Mcclain",
    "title": "Kindergarten",
    "positionType": "Teacher - Specialty (K-4)",
    "locationFirst": "Middle School",
    "locationTwo": "Middle School",
    "location": "Middle School Middle School",
    "internal": false,
    "status": "Keep on File",
    "budgetCode": "6050-District Office"
  },
  {
    "id": 43,
    "reportsTo": "Sherrie Preston",
    "title": "Guidance Counselor (1)",
    "positionType": "Teacher - Specialty (K-4)",
    "locationFirst": "Elementary",
    "locationTwo": "Elementary",
    "location": "Elementary Elementary",
    "internal": true,
    "status": "Interviewed",
    "budgetCode": "6060-Administrators"
  },
  {
    "id": 44,
    "reportsTo": "Lancaster Roberts",
    "title": "Science Teacher",
    "positionType": "Teacher - Sci - (5-8)",
    "locationFirst": "Middle School",
    "locationTwo": "Elementary",
    "location": "Middle School Elementary",
    "internal": false,
    "status": "Interviewed",
    "budgetCode": "6030-General Support"
  },
  {
    "id": 45,
    "reportsTo": "Lee Morse",
    "title": "Geo (4)",
    "positionType": "PSR Teacher (K-4)",
    "locationFirst": "High School",
    "locationTwo": "Elementary",
    "location": "High School Elementary",
    "internal": false,
    "status": "Keep on File",
    "budgetCode": "6010-Base"
  },
  {
    "id": 46,
    "reportsTo": "Louella Mcbride",
    "title": "PIG/Econ",
    "positionType": "Support Teacher K-4",
    "locationFirst": "Elementary",
    "locationTwo": "Middle School",
    "location": "Elementary Middle School",
    "internal": false,
    "status": "Withdrawn",
    "budgetCode": "6070-Tax"
  },
  {
    "id": 47,
    "reportsTo": "Ayers Robinson",
    "title": "Math Specialist (4)",
    "positionType": "Receptionist",
    "locationFirst": "High School",
    "locationTwo": "High School",
    "location": "High School High School",
    "internal": false,
    "status": "Interviewed",
    "budgetCode": "6010-Base"
  },
  {
    "id": 48,
    "reportsTo": "Tamika Russell",
    "title": "Social Worker (6)",
    "positionType": "Director",
    "locationFirst": "Elementary",
    "locationTwo": "High School",
    "location": "Elementary High School",
    "internal": false,
    "status": "Withdrawn",
    "budgetCode": "6060-Administrators"
  },
  {
    "id": 49,
    "reportsTo": "Natalie Mccarthy",
    "title": "PIG/Econ",
    "positionType": "Teacher - Elementary",
    "locationFirst": "Middle School",
    "locationTwo": "Middle School",
    "location": "Middle School Middle School",
    "internal": true,
    "status": "Hiring in Process",
    "budgetCode": "6060-Administrators"
  },
  {
    "id": 50,
    "reportsTo": "Melva Rivas",
    "title": "Social Worker (6)",
    "positionType": "Teacher - Elementary",
    "locationFirst": "BuffSci 2",
    "locationTwo": "BuffSci 2",
    "location": "BuffSci 2 BuffSci 2",
    "internal": false,
    "status": "Interview Scheduled",
    "budgetCode": "6070-Tax"
  },
  {
    "id": 51,
    "reportsTo": "Gena Frederick",
    "title": "Cleaning Crew",
    "positionType": "Executive Director",
    "locationFirst": "Middle School",
    "locationTwo": "High School",
    "location": "Middle School High School",
    "internal": true,
    "status": "Keep on File",
    "budgetCode": "6060-Administrators"
  },
  {
    "id": 52,
    "reportsTo": "Deena Powers",
    "title": "Math Specialist (4)",
    "positionType": "Help Desk Technician",
    "locationFirst": "Elementary",
    "locationTwo": "High School",
    "location": "Elementary High School",
    "internal": true,
    "status": "Interviewed",
    "budgetCode": "6060-Administrators"
  },
  {
    "id": 53,
    "reportsTo": "Cross Alford",
    "title": "Data Coordinator",
    "positionType": "Help Desk Technician",
    "locationFirst": "BuffSci 2",
    "locationTwo": "High School",
    "location": "BuffSci 2 High School",
    "internal": false,
    "status": "Keep on File",
    "budgetCode": "6050-District Office"
  }
]
export {positions};